### ISSUE TITLE
Error: No item found

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [Ookamini95/Project-1---iTunes-Api#4]
MY GOOD FRIEND PLEASE FIX THIS ISSUE BECAUSE INCREASE FEW RESULTS!PLEASE MY GOOD FRIEND!

Error: No item found APP JS 54   Error finding song...

**Comment by Ookamini95** [comment]
This is a learning project, not a paid one. Will focus on design from now on ( no more functionalities, sorry )
